version: '3'

services:
  tinymediamanager_service:
    image: dzhuang/tinymediamanager:latest-v5
    container_name: tinymediamanager-v5
    ports:
      - 5800:5800
      - 5900:5900
    volumes:
      - ./config:/config
      - ./media:/media
    environment:
      GROUP_ID: 1000
      USER_ID: 0
      TZ: Asia/Hong_Kong

  # Enable image/container auto update
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Asia/Shanghai
    command: --interval 3600 tinymediamanager-v5 --cleanup
